//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Repository.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacilityEventType
    {
        public int FacilityEventTypeId { get; set; }
        public int FacilityId { get; set; }
        public int EventTypeId { get; set; }
    
        public virtual EventType EventType { get; set; }
        public virtual Facility Facility { get; set; }
    }
}
