//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Repository.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPassword
    {
        public int UserPasswordId { get; set; }
        public int UserId { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual User User { get; set; }
    }
}
