//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public int CurrencyId { get; set; }
        public string CurrencyCode { get; set; }
        public string Symbol { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime CreatedBy { get; set; }
    }
}
