//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility
    {
        public int FacilityId { get; set; }
        public int VenueId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<int> MinPack { get; set; }
        public Nullable<int> MaxPack { get; set; }
        public Nullable<int> StyleId { get; set; }
        public Nullable<decimal> MinBudget { get; set; }
        public Nullable<decimal> MaxBudget { get; set; }
        public string Comments { get; set; }
    
        public virtual Facility Facility1 { get; set; }
        public virtual Facility Facility2 { get; set; }
    }
}
